server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: jdbc:h2:mem:~/testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://lemur-6.cloud-iam.com/auth/realms/securityworkshop
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs



#keycloak:
#  realm: securityworkshop
#  auth-server-url: https://lemur-6.cloud-iam.com/auth
#  resource: springboot-keycloak
#  public-client: true
#  bearer-only: true

